[build]
  command = "npm run build"
  publish = "public"

[context.production.environment]
  NODE_VERSION = "16.11.1"
  NPM_VERSION = "8.0.0"

[context.deploy-preview.environment]
  NODE_VERSION = "16.11.1"
  NPM_VERSION = "8.0.0"
